### ISSUE TITLE
ci retry on commit error

### ISSUE THREAD

**Issue by messense** [bosondata/badwolf#2]
```
 'git checkout be9660b026e203e1fbf9dc5bc456050aed9eb72a' returned with exit code 128 stderr: 'fatal: reference is not a tree: be9660b026e203e1fbf9dc5bc456050aed9eb72a'
```

**Comment by messense** [comment]
Better strategy: https://github.com/bosondata/badwolf/commit/b8977fa7a25f0f04042cd503d7c910420872af15

**Comment by messense** [comment]
```
2017-04-20 02:03:29,772 INFO Process-12 badwolf.cloner.clone:44    Unshallowing a shallow cloned repository
2017-04-20 02:03:44,462 INFO Process-12 badwolf.cloner.clone:46    Checkout commit 997707b322dedc483382e8e00a7642cecc942484
2017-04-20 02:03:44,468 ERROR Process-12 badwolf.pipeline.start:54    Git command error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/badwolf/pipeline.py", line 47, in start
    self.clone()
  File "/usr/local/lib/python3.6/dist-packages/badwolf/pipeline.py", line 97, in clone
    RepositoryCloner(self.context).clone()
  File "/usr/local/lib/python3.6/dist-packages/badwolf/cloner.py", line 47, in clone
    gitcmd.checkout(self.commit_hash)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 425, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 688, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git checkout 997707b322dedc483382e8e00a7642cecc942484
  stderr: 'fatal: reference is not a tree: 997707b322dedc483382e8e00a7642cecc942484'
```

**Comment by messense** [comment]
```
Cmd('git') failed due to: exit code(128) cmdline: git fetch --unshallow stderr: 'fatal: --unshallow on a complete repository does not make sense'
```

**Comment by messense** [comment]
Should be fixed in https://github.com/bosondata/badwolf/commit/80b991c35b3114f6d4ceb0fa5283290f23004965
